// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: internal/protocol/wirepb/wideboi.proto

package wirepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerbType int32

const (
	VerbType_VERB_TYPE_UNSPECIFIED  VerbType = 0
	VerbType_VERB_TYPE_FOCUS_LEFT   VerbType = 1
	VerbType_VERB_TYPE_FOCUS_RIGHT  VerbType = 2
	VerbType_VERB_TYPE_NEW_COLUMN   VerbType = 3
	VerbType_VERB_TYPE_CYCLE_WIDTH  VerbType = 4
	VerbType_VERB_TYPE_KILL_PANE    VerbType = 5
	VerbType_VERB_TYPE_SMART_JUMP   VerbType = 6
	VerbType_VERB_TYPE_TOGGLE_CARDS VerbType = 7
	VerbType_VERB_TYPE_GROW_WIDTH   VerbType = 8
	VerbType_VERB_TYPE_SHRINK_WIDTH VerbType = 9
	VerbType_VERB_TYPE_MOVE_LEFT    VerbType = 10
	VerbType_VERB_TYPE_MOVE_RIGHT   VerbType = 11
	VerbType_VERB_TYPE_FOCUS_LAST   VerbType = 12
)

// Enum value maps for VerbType.
var (
	VerbType_name = map[int32]string{
		0:  "VERB_TYPE_UNSPECIFIED",
		1:  "VERB_TYPE_FOCUS_LEFT",
		2:  "VERB_TYPE_FOCUS_RIGHT",
		3:  "VERB_TYPE_NEW_COLUMN",
		4:  "VERB_TYPE_CYCLE_WIDTH",
		5:  "VERB_TYPE_KILL_PANE",
		6:  "VERB_TYPE_SMART_JUMP",
		7:  "VERB_TYPE_TOGGLE_CARDS",
		8:  "VERB_TYPE_GROW_WIDTH",
		9:  "VERB_TYPE_SHRINK_WIDTH",
		10: "VERB_TYPE_MOVE_LEFT",
		11: "VERB_TYPE_MOVE_RIGHT",
		12: "VERB_TYPE_FOCUS_LAST",
	}
	VerbType_value = map[string]int32{
		"VERB_TYPE_UNSPECIFIED":  0,
		"VERB_TYPE_FOCUS_LEFT":   1,
		"VERB_TYPE_FOCUS_RIGHT":  2,
		"VERB_TYPE_NEW_COLUMN":   3,
		"VERB_TYPE_CYCLE_WIDTH":  4,
		"VERB_TYPE_KILL_PANE":    5,
		"VERB_TYPE_SMART_JUMP":   6,
		"VERB_TYPE_TOGGLE_CARDS": 7,
		"VERB_TYPE_GROW_WIDTH":   8,
		"VERB_TYPE_SHRINK_WIDTH": 9,
		"VERB_TYPE_MOVE_LEFT":    10,
		"VERB_TYPE_MOVE_RIGHT":   11,
		"VERB_TYPE_FOCUS_LAST":   12,
	}
)

func (x VerbType) Enum() *VerbType {
	p := new(VerbType)
	*p = x
	return p
}

func (x VerbType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerbType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_wirepb_wideboi_proto_enumTypes[0].Descriptor()
}

func (VerbType) Type() protoreflect.EnumType {
	return &file_internal_protocol_wirepb_wideboi_proto_enumTypes[0]
}

func (x VerbType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerbType.Descriptor instead.
func (VerbType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{0}
}

type PaneStatus int32

const (
	PaneStatus_PANE_STATUS_IDLE        PaneStatus = 0
	PaneStatus_PANE_STATUS_WORKING     PaneStatus = 1
	PaneStatus_PANE_STATUS_NEEDS_INPUT PaneStatus = 2
	PaneStatus_PANE_STATUS_DONE        PaneStatus = 3
	PaneStatus_PANE_STATUS_FAILED      PaneStatus = 4
)

// Enum value maps for PaneStatus.
var (
	PaneStatus_name = map[int32]string{
		0: "PANE_STATUS_IDLE",
		1: "PANE_STATUS_WORKING",
		2: "PANE_STATUS_NEEDS_INPUT",
		3: "PANE_STATUS_DONE",
		4: "PANE_STATUS_FAILED",
	}
	PaneStatus_value = map[string]int32{
		"PANE_STATUS_IDLE":        0,
		"PANE_STATUS_WORKING":     1,
		"PANE_STATUS_NEEDS_INPUT": 2,
		"PANE_STATUS_DONE":        3,
		"PANE_STATUS_FAILED":      4,
	}
)

func (x PaneStatus) Enum() *PaneStatus {
	p := new(PaneStatus)
	*p = x
	return p
}

func (x PaneStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaneStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_wirepb_wideboi_proto_enumTypes[1].Descriptor()
}

func (PaneStatus) Type() protoreflect.EnumType {
	return &file_internal_protocol_wirepb_wideboi_proto_enumTypes[1]
}

func (x PaneStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaneStatus.Descriptor instead.
func (PaneStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{1}
}

type ColorKind int32

const (
	ColorKind_COLOR_KIND_NONE    ColorKind = 0
	ColorKind_COLOR_KIND_BASIC   ColorKind = 1
	ColorKind_COLOR_KIND_INDEXED ColorKind = 2
	ColorKind_COLOR_KIND_RGBA    ColorKind = 3
)

// Enum value maps for ColorKind.
var (
	ColorKind_name = map[int32]string{
		0: "COLOR_KIND_NONE",
		1: "COLOR_KIND_BASIC",
		2: "COLOR_KIND_INDEXED",
		3: "COLOR_KIND_RGBA",
	}
	ColorKind_value = map[string]int32{
		"COLOR_KIND_NONE":    0,
		"COLOR_KIND_BASIC":   1,
		"COLOR_KIND_INDEXED": 2,
		"COLOR_KIND_RGBA":    3,
	}
)

func (x ColorKind) Enum() *ColorKind {
	p := new(ColorKind)
	*p = x
	return p
}

func (x ColorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_wirepb_wideboi_proto_enumTypes[2].Descriptor()
}

func (ColorKind) Type() protoreflect.EnumType {
	return &file_internal_protocol_wirepb_wideboi_proto_enumTypes[2]
}

func (x ColorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorKind.Descriptor instead.
func (ColorKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{2}
}

type MouseKind int32

const (
	MouseKind_MOUSE_KIND_PRESS   MouseKind = 0
	MouseKind_MOUSE_KIND_RELEASE MouseKind = 1
	MouseKind_MOUSE_KIND_MOTION  MouseKind = 2
	MouseKind_MOUSE_KIND_WHEEL   MouseKind = 3
)

// Enum value maps for MouseKind.
var (
	MouseKind_name = map[int32]string{
		0: "MOUSE_KIND_PRESS",
		1: "MOUSE_KIND_RELEASE",
		2: "MOUSE_KIND_MOTION",
		3: "MOUSE_KIND_WHEEL",
	}
	MouseKind_value = map[string]int32{
		"MOUSE_KIND_PRESS":   0,
		"MOUSE_KIND_RELEASE": 1,
		"MOUSE_KIND_MOTION":  2,
		"MOUSE_KIND_WHEEL":   3,
	}
)

func (x MouseKind) Enum() *MouseKind {
	p := new(MouseKind)
	*p = x
	return p
}

func (x MouseKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MouseKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_wirepb_wideboi_proto_enumTypes[3].Descriptor()
}

func (MouseKind) Type() protoreflect.EnumType {
	return &file_internal_protocol_wirepb_wideboi_proto_enumTypes[3]
}

func (x MouseKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MouseKind.Descriptor instead.
func (MouseKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{3}
}

type ColorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ColorKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=wideboi.protocol.ColorKind" json:"kind,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	R             uint32                 `protobuf:"varint,3,opt,name=r,proto3" json:"r,omitempty"`
	G             uint32                 `protobuf:"varint,4,opt,name=g,proto3" json:"g,omitempty"`
	B             uint32                 `protobuf:"varint,5,opt,name=b,proto3" json:"b,omitempty"`
	A             uint32                 `protobuf:"varint,6,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorData) Reset() {
	*x = ColorData{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorData) ProtoMessage() {}

func (x *ColorData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorData.ProtoReflect.Descriptor instead.
func (*ColorData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{0}
}

func (x *ColorData) GetKind() ColorKind {
	if x != nil {
		return x.Kind
	}
	return ColorKind_COLOR_KIND_NONE
}

func (x *ColorData) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ColorData) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *ColorData) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *ColorData) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *ColorData) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

type StyleData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Fg             *ColorData             `protobuf:"bytes,1,opt,name=fg,proto3" json:"fg,omitempty"`
	Bg             *ColorData             `protobuf:"bytes,2,opt,name=bg,proto3" json:"bg,omitempty"`
	UnderlineColor *ColorData             `protobuf:"bytes,3,opt,name=underline_color,json=underlineColor,proto3" json:"underline_color,omitempty"`
	Underline      uint32                 `protobuf:"varint,4,opt,name=underline,proto3" json:"underline,omitempty"`
	Attrs          uint32                 `protobuf:"varint,5,opt,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StyleData) Reset() {
	*x = StyleData{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StyleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StyleData) ProtoMessage() {}

func (x *StyleData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StyleData.ProtoReflect.Descriptor instead.
func (*StyleData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{1}
}

func (x *StyleData) GetFg() *ColorData {
	if x != nil {
		return x.Fg
	}
	return nil
}

func (x *StyleData) GetBg() *ColorData {
	if x != nil {
		return x.Bg
	}
	return nil
}

func (x *StyleData) GetUnderlineColor() *ColorData {
	if x != nil {
		return x.UnderlineColor
	}
	return nil
}

func (x *StyleData) GetUnderline() uint32 {
	if x != nil {
		return x.Underline
	}
	return 0
}

func (x *StyleData) GetAttrs() uint32 {
	if x != nil {
		return x.Attrs
	}
	return 0
}

type CellData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Style         *StyleData             `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellData) Reset() {
	*x = CellData{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellData) ProtoMessage() {}

func (x *CellData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellData.ProtoReflect.Descriptor instead.
func (*CellData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{2}
}

func (x *CellData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CellData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CellData) GetStyle() *StyleData {
	if x != nil {
		return x.Style
	}
	return nil
}

type LineData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*CellData            `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineData) Reset() {
	*x = LineData{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineData) ProtoMessage() {}

func (x *LineData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineData.ProtoReflect.Descriptor instead.
func (*LineData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{3}
}

func (x *LineData) GetCells() []*CellData {
	if x != nil {
		return x.Cells
	}
	return nil
}

// Generations arrive in the browser as bigint (protobuf-es ignores
// jstype = JS_NUMBER). Compare them only with other generations.
type MsgPaneUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Cols          int32                  `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	Lines         []*LineData            `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	CursorX       int32                  `protobuf:"varint,6,opt,name=cursor_x,json=cursorX,proto3" json:"cursor_x,omitempty"`
	CursorY       int32                  `protobuf:"varint,7,opt,name=cursor_y,json=cursorY,proto3" json:"cursor_y,omitempty"`
	CursorVisible bool                   `protobuf:"varint,8,opt,name=cursor_visible,json=cursorVisible,proto3" json:"cursor_visible,omitempty"`
	MouseTracking bool                   `protobuf:"varint,9,opt,name=mouse_tracking,json=mouseTracking,proto3" json:"mouse_tracking,omitempty"`
	ScrollOffset  int32                  `protobuf:"varint,10,opt,name=scroll_offset,json=scrollOffset,proto3" json:"scroll_offset,omitempty"`
	ScrollbackLen int32                  `protobuf:"varint,11,opt,name=scrollback_len,json=scrollbackLen,proto3" json:"scrollback_len,omitempty"`
	UnreadOutput  bool                   `protobuf:"varint,12,opt,name=unread_output,json=unreadOutput,proto3" json:"unread_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPaneUpdate) Reset() {
	*x = MsgPaneUpdate{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPaneUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPaneUpdate) ProtoMessage() {}

func (x *MsgPaneUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPaneUpdate.ProtoReflect.Descriptor instead.
func (*MsgPaneUpdate) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{4}
}

func (x *MsgPaneUpdate) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgPaneUpdate) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *MsgPaneUpdate) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *MsgPaneUpdate) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *MsgPaneUpdate) GetLines() []*LineData {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *MsgPaneUpdate) GetCursorX() int32 {
	if x != nil {
		return x.CursorX
	}
	return 0
}

func (x *MsgPaneUpdate) GetCursorY() int32 {
	if x != nil {
		return x.CursorY
	}
	return 0
}

func (x *MsgPaneUpdate) GetCursorVisible() bool {
	if x != nil {
		return x.CursorVisible
	}
	return false
}

func (x *MsgPaneUpdate) GetMouseTracking() bool {
	if x != nil {
		return x.MouseTracking
	}
	return false
}

func (x *MsgPaneUpdate) GetScrollOffset() int32 {
	if x != nil {
		return x.ScrollOffset
	}
	return 0
}

func (x *MsgPaneUpdate) GetScrollbackLen() int32 {
	if x != nil {
		return x.ScrollbackLen
	}
	return 0
}

func (x *MsgPaneUpdate) GetUnreadOutput() bool {
	if x != nil {
		return x.UnreadOutput
	}
	return false
}

// PaneRow replaces one complete row, style and wide-glyph continuations
// included.
type PaneRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Y             int32                  `protobuf:"varint,1,opt,name=y,proto3" json:"y,omitempty"`
	Cells         []*CellData            `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaneRow) Reset() {
	*x = PaneRow{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaneRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaneRow) ProtoMessage() {}

func (x *PaneRow) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaneRow.ProtoReflect.Descriptor instead.
func (*PaneRow) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{5}
}

func (x *PaneRow) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PaneRow) GetCells() []*CellData {
	if x != nil {
		return x.Cells
	}
	return nil
}

// MsgPanePatch changes a pane relative to an exact client baseline. Its
// cursor and mouse fields always overwrite; rows may be empty.
type MsgPanePatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaneId         int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Cols           int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows           int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	BaseGeneration uint64                 `protobuf:"varint,4,opt,name=base_generation,json=baseGeneration,proto3" json:"base_generation,omitempty"`
	Generation     uint64                 `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	ChangedRows    []*PaneRow             `protobuf:"bytes,6,rep,name=changed_rows,json=changedRows,proto3" json:"changed_rows,omitempty"`
	CursorX        int32                  `protobuf:"varint,7,opt,name=cursor_x,json=cursorX,proto3" json:"cursor_x,omitempty"`
	CursorY        int32                  `protobuf:"varint,8,opt,name=cursor_y,json=cursorY,proto3" json:"cursor_y,omitempty"`
	CursorVisible  bool                   `protobuf:"varint,9,opt,name=cursor_visible,json=cursorVisible,proto3" json:"cursor_visible,omitempty"`
	MouseTracking  bool                   `protobuf:"varint,10,opt,name=mouse_tracking,json=mouseTracking,proto3" json:"mouse_tracking,omitempty"`
	ShiftRows      int32                  `protobuf:"varint,11,opt,name=shift_rows,json=shiftRows,proto3" json:"shift_rows,omitempty"`
	ScrollOffset   int32                  `protobuf:"varint,12,opt,name=scroll_offset,json=scrollOffset,proto3" json:"scroll_offset,omitempty"`
	ScrollbackLen  int32                  `protobuf:"varint,13,opt,name=scrollback_len,json=scrollbackLen,proto3" json:"scrollback_len,omitempty"`
	UnreadOutput   bool                   `protobuf:"varint,14,opt,name=unread_output,json=unreadOutput,proto3" json:"unread_output,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgPanePatch) Reset() {
	*x = MsgPanePatch{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPanePatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPanePatch) ProtoMessage() {}

func (x *MsgPanePatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPanePatch.ProtoReflect.Descriptor instead.
func (*MsgPanePatch) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{6}
}

func (x *MsgPanePatch) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgPanePatch) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *MsgPanePatch) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *MsgPanePatch) GetBaseGeneration() uint64 {
	if x != nil {
		return x.BaseGeneration
	}
	return 0
}

func (x *MsgPanePatch) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *MsgPanePatch) GetChangedRows() []*PaneRow {
	if x != nil {
		return x.ChangedRows
	}
	return nil
}

func (x *MsgPanePatch) GetCursorX() int32 {
	if x != nil {
		return x.CursorX
	}
	return 0
}

func (x *MsgPanePatch) GetCursorY() int32 {
	if x != nil {
		return x.CursorY
	}
	return 0
}

func (x *MsgPanePatch) GetCursorVisible() bool {
	if x != nil {
		return x.CursorVisible
	}
	return false
}

func (x *MsgPanePatch) GetMouseTracking() bool {
	if x != nil {
		return x.MouseTracking
	}
	return false
}

func (x *MsgPanePatch) GetShiftRows() int32 {
	if x != nil {
		return x.ShiftRows
	}
	return 0
}

func (x *MsgPanePatch) GetScrollOffset() int32 {
	if x != nil {
		return x.ScrollOffset
	}
	return 0
}

func (x *MsgPanePatch) GetScrollbackLen() int32 {
	if x != nil {
		return x.ScrollbackLen
	}
	return 0
}

func (x *MsgPanePatch) GetUnreadOutput() bool {
	if x != nil {
		return x.UnreadOutput
	}
	return false
}

type ColumnData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnData) Reset() {
	*x = ColumnData{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnData) ProtoMessage() {}

func (x *ColumnData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnData.ProtoReflect.Descriptor instead.
func (*ColumnData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{7}
}

func (x *ColumnData) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *ColumnData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ColumnData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type MsgLayoutSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*ColumnData          `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	PaneStatuses  map[int32]PaneStatus   `protobuf:"bytes,2,rep,name=pane_statuses,json=paneStatuses,proto3" json:"pane_statuses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=wideboi.protocol.PaneStatus"`
	PaneTitles    map[int32]string       `protobuf:"bytes,3,rep,name=pane_titles,json=paneTitles,proto3" json:"pane_titles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgLayoutSnapshot) Reset() {
	*x = MsgLayoutSnapshot{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgLayoutSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLayoutSnapshot) ProtoMessage() {}

func (x *MsgLayoutSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLayoutSnapshot.ProtoReflect.Descriptor instead.
func (*MsgLayoutSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{8}
}

func (x *MsgLayoutSnapshot) GetColumns() []*ColumnData {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *MsgLayoutSnapshot) GetPaneStatuses() map[int32]PaneStatus {
	if x != nil {
		return x.PaneStatuses
	}
	return nil
}

func (x *MsgLayoutSnapshot) GetPaneTitles() map[int32]string {
	if x != nil {
		return x.PaneTitles
	}
	return nil
}

type MsgPaneCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPaneCreated) Reset() {
	*x = MsgPaneCreated{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPaneCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPaneCreated) ProtoMessage() {}

func (x *MsgPaneCreated) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPaneCreated.ProtoReflect.Descriptor instead.
func (*MsgPaneCreated) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{9}
}

func (x *MsgPaneCreated) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

type MsgPaneClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPaneClosed) Reset() {
	*x = MsgPaneClosed{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPaneClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPaneClosed) ProtoMessage() {}

func (x *MsgPaneClosed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPaneClosed.ProtoReflect.Descriptor instead.
func (*MsgPaneClosed) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{10}
}

func (x *MsgPaneClosed) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgPaneClosed) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type MsgPaneMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Cwd           string                 `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	UserVars      map[string]string      `protobuf:"bytes,3,rep,name=user_vars,json=userVars,proto3" json:"user_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPaneMetadata) Reset() {
	*x = MsgPaneMetadata{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPaneMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPaneMetadata) ProtoMessage() {}

func (x *MsgPaneMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPaneMetadata.ProtoReflect.Descriptor instead.
func (*MsgPaneMetadata) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{11}
}

func (x *MsgPaneMetadata) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgPaneMetadata) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *MsgPaneMetadata) GetUserVars() map[string]string {
	if x != nil {
		return x.UserVars
	}
	return nil
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_PaneUpdate
	//	*ServerMessage_PanePatch
	//	*ServerMessage_LayoutSnapshot
	//	*ServerMessage_PaneCreated
	//	*ServerMessage_PaneClosed
	//	*ServerMessage_PaneMetadata
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{12}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetPaneUpdate() *MsgPaneUpdate {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_PaneUpdate); ok {
			return x.PaneUpdate
		}
	}
	return nil
}

func (x *ServerMessage) GetPanePatch() *MsgPanePatch {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_PanePatch); ok {
			return x.PanePatch
		}
	}
	return nil
}

func (x *ServerMessage) GetLayoutSnapshot() *MsgLayoutSnapshot {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_LayoutSnapshot); ok {
			return x.LayoutSnapshot
		}
	}
	return nil
}

func (x *ServerMessage) GetPaneCreated() *MsgPaneCreated {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_PaneCreated); ok {
			return x.PaneCreated
		}
	}
	return nil
}

func (x *ServerMessage) GetPaneClosed() *MsgPaneClosed {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_PaneClosed); ok {
			return x.PaneClosed
		}
	}
	return nil
}

func (x *ServerMessage) GetPaneMetadata() *MsgPaneMetadata {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_PaneMetadata); ok {
			return x.PaneMetadata
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_PaneUpdate struct {
	PaneUpdate *MsgPaneUpdate `protobuf:"bytes,1,opt,name=pane_update,json=paneUpdate,proto3,oneof"`
}

type ServerMessage_PanePatch struct {
	PanePatch *MsgPanePatch `protobuf:"bytes,2,opt,name=pane_patch,json=panePatch,proto3,oneof"`
}

type ServerMessage_LayoutSnapshot struct {
	LayoutSnapshot *MsgLayoutSnapshot `protobuf:"bytes,3,opt,name=layout_snapshot,json=layoutSnapshot,proto3,oneof"`
}

type ServerMessage_PaneCreated struct {
	PaneCreated *MsgPaneCreated `protobuf:"bytes,4,opt,name=pane_created,json=paneCreated,proto3,oneof"`
}

type ServerMessage_PaneClosed struct {
	PaneClosed *MsgPaneClosed `protobuf:"bytes,5,opt,name=pane_closed,json=paneClosed,proto3,oneof"`
}

type ServerMessage_PaneMetadata struct {
	PaneMetadata *MsgPaneMetadata `protobuf:"bytes,6,opt,name=pane_metadata,json=paneMetadata,proto3,oneof"`
}

func (*ServerMessage_PaneUpdate) isServerMessage_Msg() {}

func (*ServerMessage_PanePatch) isServerMessage_Msg() {}

func (*ServerMessage_LayoutSnapshot) isServerMessage_Msg() {}

func (*ServerMessage_PaneCreated) isServerMessage_Msg() {}

func (*ServerMessage_PaneClosed) isServerMessage_Msg() {}

func (*ServerMessage_PaneMetadata) isServerMessage_Msg() {}

type MsgAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          int32                  `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAttach) Reset() {
	*x = MsgAttach{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAttach) ProtoMessage() {}

func (x *MsgAttach) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAttach.ProtoReflect.Descriptor instead.
func (*MsgAttach) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{13}
}

func (x *MsgAttach) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *MsgAttach) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type MsgVerb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verb          VerbType               `protobuf:"varint,1,opt,name=verb,proto3,enum=wideboi.protocol.VerbType" json:"verb,omitempty"`
	PaneId        int32                  `protobuf:"varint,2,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgVerb) Reset() {
	*x = MsgVerb{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgVerb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVerb) ProtoMessage() {}

func (x *MsgVerb) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVerb.ProtoReflect.Descriptor instead.
func (*MsgVerb) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{14}
}

func (x *MsgVerb) GetVerb() VerbType {
	if x != nil {
		return x.Verb
	}
	return VerbType_VERB_TYPE_UNSPECIFIED
}

func (x *MsgVerb) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

type MsgMouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Kind          MouseKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=wideboi.protocol.MouseKind" json:"kind,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Button        int32                  `protobuf:"varint,5,opt,name=button,proto3" json:"button,omitempty"`
	Mod           int32                  `protobuf:"varint,6,opt,name=mod,proto3" json:"mod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMouse) Reset() {
	*x = MsgMouse{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMouse) ProtoMessage() {}

func (x *MsgMouse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMouse.ProtoReflect.Descriptor instead.
func (*MsgMouse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{15}
}

func (x *MsgMouse) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgMouse) GetKind() MouseKind {
	if x != nil {
		return x.Kind
	}
	return MouseKind_MOUSE_KIND_PRESS
}

func (x *MsgMouse) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MsgMouse) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MsgMouse) GetButton() int32 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *MsgMouse) GetMod() int32 {
	if x != nil {
		return x.Mod
	}
	return 0
}

type KeyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Mod           int32                  `protobuf:"varint,2,opt,name=mod,proto3" json:"mod,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	ShiftedCode   int32                  `protobuf:"varint,4,opt,name=shifted_code,json=shiftedCode,proto3" json:"shifted_code,omitempty"`
	BaseCode      int32                  `protobuf:"varint,5,opt,name=base_code,json=baseCode,proto3" json:"base_code,omitempty"`
	IsRepeat      bool                   `protobuf:"varint,6,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyData) Reset() {
	*x = KeyData{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyData) ProtoMessage() {}

func (x *KeyData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyData.ProtoReflect.Descriptor instead.
func (*KeyData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{16}
}

func (x *KeyData) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *KeyData) GetMod() int32 {
	if x != nil {
		return x.Mod
	}
	return 0
}

func (x *KeyData) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *KeyData) GetShiftedCode() int32 {
	if x != nil {
		return x.ShiftedCode
	}
	return 0
}

func (x *KeyData) GetBaseCode() int32 {
	if x != nil {
		return x.BaseCode
	}
	return 0
}

func (x *KeyData) GetIsRepeat() bool {
	if x != nil {
		return x.IsRepeat
	}
	return false
}

type MsgInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Key           *KeyData               `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgInput) Reset() {
	*x = MsgInput{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInput) ProtoMessage() {}

func (x *MsgInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInput.ProtoReflect.Descriptor instead.
func (*MsgInput) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{17}
}

func (x *MsgInput) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgInput) GetKey() *KeyData {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MsgInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MsgResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          int32                  `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgResize) Reset() {
	*x = MsgResize{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResize) ProtoMessage() {}

func (x *MsgResize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResize.ProtoReflect.Descriptor instead.
func (*MsgResize) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{18}
}

func (x *MsgResize) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *MsgResize) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type MsgScroll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgScroll) Reset() {
	*x = MsgScroll{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgScroll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgScroll) ProtoMessage() {}

func (x *MsgScroll) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgScroll.ProtoReflect.Descriptor instead.
func (*MsgScroll) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{19}
}

func (x *MsgScroll) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgScroll) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type MsgPaneResync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPaneResync) Reset() {
	*x = MsgPaneResync{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPaneResync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPaneResync) ProtoMessage() {}

func (x *MsgPaneResync) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPaneResync.ProtoReflect.Descriptor instead.
func (*MsgPaneResync) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{20}
}

func (x *MsgPaneResync) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

type MsgDetach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDetach) Reset() {
	*x = MsgDetach{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDetach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDetach) ProtoMessage() {}

func (x *MsgDetach) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDetach.ProtoReflect.Descriptor instead.
func (*MsgDetach) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{21}
}

type MsgShutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgShutdown) Reset() {
	*x = MsgShutdown{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgShutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgShutdown) ProtoMessage() {}

func (x *MsgShutdown) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgShutdown.ProtoReflect.Descriptor instead.
func (*MsgShutdown) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{22}
}

type MsgStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgStatusRequest) Reset() {
	*x = MsgStatusRequest{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStatusRequest) ProtoMessage() {}

func (x *MsgStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStatusRequest.ProtoReflect.Descriptor instead.
func (*MsgStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{23}
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_Attach
	//	*ClientMessage_Verb
	//	*ClientMessage_Mouse
	//	*ClientMessage_Input
	//	*ClientMessage_Resize
	//	*ClientMessage_Scroll
	//	*ClientMessage_PaneResync
	//	*ClientMessage_Detach
	//	*ClientMessage_Shutdown
	//	*ClientMessage_StatusRequest
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wirepb_wideboi_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP(), []int{24}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetAttach() *MsgAttach {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Attach); ok {
			return x.Attach
		}
	}
	return nil
}

func (x *ClientMessage) GetVerb() *MsgVerb {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Verb); ok {
			return x.Verb
		}
	}
	return nil
}

func (x *ClientMessage) GetMouse() *MsgMouse {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Mouse); ok {
			return x.Mouse
		}
	}
	return nil
}

func (x *ClientMessage) GetInput() *MsgInput {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ClientMessage) GetResize() *MsgResize {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ClientMessage) GetScroll() *MsgScroll {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Scroll); ok {
			return x.Scroll
		}
	}
	return nil
}

func (x *ClientMessage) GetPaneResync() *MsgPaneResync {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_PaneResync); ok {
			return x.PaneResync
		}
	}
	return nil
}

func (x *ClientMessage) GetDetach() *MsgDetach {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Detach); ok {
			return x.Detach
		}
	}
	return nil
}

func (x *ClientMessage) GetShutdown() *MsgShutdown {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ClientMessage) GetStatusRequest() *MsgStatusRequest {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_StatusRequest); ok {
			return x.StatusRequest
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_Attach struct {
	Attach *MsgAttach `protobuf:"bytes,1,opt,name=attach,proto3,oneof"`
}

type ClientMessage_Verb struct {
	Verb *MsgVerb `protobuf:"bytes,2,opt,name=verb,proto3,oneof"`
}

type ClientMessage_Mouse struct {
	Mouse *MsgMouse `protobuf:"bytes,3,opt,name=mouse,proto3,oneof"`
}

type ClientMessage_Input struct {
	Input *MsgInput `protobuf:"bytes,4,opt,name=input,proto3,oneof"`
}

type ClientMessage_Resize struct {
	Resize *MsgResize `protobuf:"bytes,5,opt,name=resize,proto3,oneof"`
}

type ClientMessage_Scroll struct {
	Scroll *MsgScroll `protobuf:"bytes,6,opt,name=scroll,proto3,oneof"`
}

type ClientMessage_PaneResync struct {
	PaneResync *MsgPaneResync `protobuf:"bytes,7,opt,name=pane_resync,json=paneResync,proto3,oneof"`
}

type ClientMessage_Detach struct {
	Detach *MsgDetach `protobuf:"bytes,8,opt,name=detach,proto3,oneof"`
}

type ClientMessage_Shutdown struct {
	Shutdown *MsgShutdown `protobuf:"bytes,9,opt,name=shutdown,proto3,oneof"`
}

type ClientMessage_StatusRequest struct {
	StatusRequest *MsgStatusRequest `protobuf:"bytes,10,opt,name=status_request,json=statusRequest,proto3,oneof"`
}

func (*ClientMessage_Attach) isClientMessage_Msg() {}

func (*ClientMessage_Verb) isClientMessage_Msg() {}

func (*ClientMessage_Mouse) isClientMessage_Msg() {}

func (*ClientMessage_Input) isClientMessage_Msg() {}

func (*ClientMessage_Resize) isClientMessage_Msg() {}

func (*ClientMessage_Scroll) isClientMessage_Msg() {}

func (*ClientMessage_PaneResync) isClientMessage_Msg() {}

func (*ClientMessage_Detach) isClientMessage_Msg() {}

func (*ClientMessage_Shutdown) isClientMessage_Msg() {}

func (*ClientMessage_StatusRequest) isClientMessage_Msg() {}

var File_internal_protocol_wirepb_wideboi_proto protoreflect.FileDescriptor

const file_internal_protocol_wirepb_wideboi_proto_rawDesc = "" +
	"\n" +
	"&internal/protocol/wirepb/wideboi.proto\x12\x10wideboi.protocol\"\x8a\x01\n" +
	"\tColorData\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.wideboi.protocol.ColorKindR\x04kind\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\f\n" +
	"\x01r\x18\x03 \x01(\rR\x01r\x12\f\n" +
	"\x01g\x18\x04 \x01(\rR\x01g\x12\f\n" +
	"\x01b\x18\x05 \x01(\rR\x01b\x12\f\n" +
	"\x01a\x18\x06 \x01(\rR\x01a\"\xdf\x01\n" +
	"\tStyleData\x12+\n" +
	"\x02fg\x18\x01 \x01(\v2\x1b.wideboi.protocol.ColorDataR\x02fg\x12+\n" +
	"\x02bg\x18\x02 \x01(\v2\x1b.wideboi.protocol.ColorDataR\x02bg\x12D\n" +
	"\x0funderline_color\x18\x03 \x01(\v2\x1b.wideboi.protocol.ColorDataR\x0eunderlineColor\x12\x1c\n" +
	"\tunderline\x18\x04 \x01(\rR\tunderline\x12\x14\n" +
	"\x05attrs\x18\x05 \x01(\rR\x05attrs\"m\n" +
	"\bCellData\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x121\n" +
	"\x05style\x18\x03 \x01(\v2\x1b.wideboi.protocol.StyleDataR\x05style\"<\n" +
	"\bLineData\x120\n" +
	"\x05cells\x18\x01 \x03(\v2\x1a.wideboi.protocol.CellDataR\x05cells\"\x97\x03\n" +
	"\rMsgPaneUpdate\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\x120\n" +
	"\x05lines\x18\x05 \x03(\v2\x1a.wideboi.protocol.LineDataR\x05lines\x12\x19\n" +
	"\bcursor_x\x18\x06 \x01(\x05R\acursorX\x12\x19\n" +
	"\bcursor_y\x18\a \x01(\x05R\acursorY\x12%\n" +
	"\x0ecursor_visible\x18\b \x01(\bR\rcursorVisible\x12%\n" +
	"\x0emouse_tracking\x18\t \x01(\bR\rmouseTracking\x12#\n" +
	"\rscroll_offset\x18\n" +
	" \x01(\x05R\fscrollOffset\x12%\n" +
	"\x0escrollback_len\x18\v \x01(\x05R\rscrollbackLen\x12#\n" +
	"\runread_output\x18\f \x01(\bR\funreadOutput\"I\n" +
	"\aPaneRow\x12\f\n" +
	"\x01y\x18\x01 \x01(\x05R\x01y\x120\n" +
	"\x05cells\x18\x02 \x03(\v2\x1a.wideboi.protocol.CellDataR\x05cells\"\xea\x03\n" +
	"\fMsgPanePatch\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\x12'\n" +
	"\x0fbase_generation\x18\x04 \x01(\x04R\x0ebaseGeneration\x12\x1e\n" +
	"\n" +
	"generation\x18\x05 \x01(\x04R\n" +
	"generation\x12<\n" +
	"\fchanged_rows\x18\x06 \x03(\v2\x19.wideboi.protocol.PaneRowR\vchangedRows\x12\x19\n" +
	"\bcursor_x\x18\a \x01(\x05R\acursorX\x12\x19\n" +
	"\bcursor_y\x18\b \x01(\x05R\acursorY\x12%\n" +
	"\x0ecursor_visible\x18\t \x01(\bR\rcursorVisible\x12%\n" +
	"\x0emouse_tracking\x18\n" +
	" \x01(\bR\rmouseTracking\x12\x1d\n" +
	"\n" +
	"shift_rows\x18\v \x01(\x05R\tshiftRows\x12#\n" +
	"\rscroll_offset\x18\f \x01(\x05R\fscrollOffset\x12%\n" +
	"\x0escrollback_len\x18\r \x01(\x05R\rscrollbackLen\x12#\n" +
	"\runread_output\x18\x0e \x01(\bR\funreadOutput\"S\n" +
	"\n" +
	"ColumnData\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"\x9b\x03\n" +
	"\x11MsgLayoutSnapshot\x126\n" +
	"\acolumns\x18\x01 \x03(\v2\x1c.wideboi.protocol.ColumnDataR\acolumns\x12Z\n" +
	"\rpane_statuses\x18\x02 \x03(\v25.wideboi.protocol.MsgLayoutSnapshot.PaneStatusesEntryR\fpaneStatuses\x12T\n" +
	"\vpane_titles\x18\x03 \x03(\v23.wideboi.protocol.MsgLayoutSnapshot.PaneTitlesEntryR\n" +
	"paneTitles\x1a]\n" +
	"\x11PaneStatusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\x0e2\x1c.wideboi.protocol.PaneStatusR\x05value:\x028\x01\x1a=\n" +
	"\x0fPaneTitlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x0eMsgPaneCreated\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\"E\n" +
	"\rMsgPaneClosed\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\"\xc7\x01\n" +
	"\x0fMsgPaneMetadata\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12L\n" +
	"\tuser_vars\x18\x03 \x03(\v2/.wideboi.protocol.MsgPaneMetadata.UserVarsEntryR\buserVars\x1a;\n" +
	"\rUserVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x03\n" +
	"\rServerMessage\x12B\n" +
	"\vpane_update\x18\x01 \x01(\v2\x1f.wideboi.protocol.MsgPaneUpdateH\x00R\n" +
	"paneUpdate\x12?\n" +
	"\n" +
	"pane_patch\x18\x02 \x01(\v2\x1e.wideboi.protocol.MsgPanePatchH\x00R\tpanePatch\x12N\n" +
	"\x0flayout_snapshot\x18\x03 \x01(\v2#.wideboi.protocol.MsgLayoutSnapshotH\x00R\x0elayoutSnapshot\x12E\n" +
	"\fpane_created\x18\x04 \x01(\v2 .wideboi.protocol.MsgPaneCreatedH\x00R\vpaneCreated\x12B\n" +
	"\vpane_closed\x18\x05 \x01(\v2\x1f.wideboi.protocol.MsgPaneClosedH\x00R\n" +
	"paneClosed\x12H\n" +
	"\rpane_metadata\x18\x06 \x01(\v2!.wideboi.protocol.MsgPaneMetadataH\x00R\fpaneMetadataB\x05\n" +
	"\x03msg\"3\n" +
	"\tMsgAttach\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\"R\n" +
	"\aMsgVerb\x12.\n" +
	"\x04verb\x18\x01 \x01(\x0e2\x1a.wideboi.protocol.VerbTypeR\x04verb\x12\x17\n" +
	"\apane_id\x18\x02 \x01(\x05R\x06paneId\"\x9a\x01\n" +
	"\bMsgMouse\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.wideboi.protocol.MouseKindR\x04kind\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x16\n" +
	"\x06button\x18\x05 \x01(\x05R\x06button\x12\x10\n" +
	"\x03mod\x18\x06 \x01(\x05R\x03mod\"\xa0\x01\n" +
	"\aKeyData\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x10\n" +
	"\x03mod\x18\x02 \x01(\x05R\x03mod\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12!\n" +
	"\fshifted_code\x18\x04 \x01(\x05R\vshiftedCode\x12\x1b\n" +
	"\tbase_code\x18\x05 \x01(\x05R\bbaseCode\x12\x1b\n" +
	"\tis_repeat\x18\x06 \x01(\bR\bisRepeat\"d\n" +
	"\bMsgInput\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12+\n" +
	"\x03key\x18\x02 \x01(\v2\x19.wideboi.protocol.KeyDataR\x03key\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"3\n" +
	"\tMsgResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\":\n" +
	"\tMsgScroll\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\"(\n" +
	"\rMsgPaneResync\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\"\v\n" +
	"\tMsgDetach\"\r\n" +
	"\vMsgShutdown\"\x12\n" +
	"\x10MsgStatusRequest\"\xd9\x04\n" +
	"\rClientMessage\x125\n" +
	"\x06attach\x18\x01 \x01(\v2\x1b.wideboi.protocol.MsgAttachH\x00R\x06attach\x12/\n" +
	"\x04verb\x18\x02 \x01(\v2\x19.wideboi.protocol.MsgVerbH\x00R\x04verb\x122\n" +
	"\x05mouse\x18\x03 \x01(\v2\x1a.wideboi.protocol.MsgMouseH\x00R\x05mouse\x122\n" +
	"\x05input\x18\x04 \x01(\v2\x1a.wideboi.protocol.MsgInputH\x00R\x05input\x125\n" +
	"\x06resize\x18\x05 \x01(\v2\x1b.wideboi.protocol.MsgResizeH\x00R\x06resize\x125\n" +
	"\x06scroll\x18\x06 \x01(\v2\x1b.wideboi.protocol.MsgScrollH\x00R\x06scroll\x12B\n" +
	"\vpane_resync\x18\a \x01(\v2\x1f.wideboi.protocol.MsgPaneResyncH\x00R\n" +
	"paneResync\x125\n" +
	"\x06detach\x18\b \x01(\v2\x1b.wideboi.protocol.MsgDetachH\x00R\x06detach\x12;\n" +
	"\bshutdown\x18\t \x01(\v2\x1d.wideboi.protocol.MsgShutdownH\x00R\bshutdown\x12K\n" +
	"\x0estatus_request\x18\n" +
	" \x01(\v2\".wideboi.protocol.MsgStatusRequestH\x00R\rstatusRequestB\x05\n" +
	"\x03msg*\xe1\x02\n" +
	"\bVerbType\x12\x19\n" +
	"\x15VERB_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14VERB_TYPE_FOCUS_LEFT\x10\x01\x12\x19\n" +
	"\x15VERB_TYPE_FOCUS_RIGHT\x10\x02\x12\x18\n" +
	"\x14VERB_TYPE_NEW_COLUMN\x10\x03\x12\x19\n" +
	"\x15VERB_TYPE_CYCLE_WIDTH\x10\x04\x12\x17\n" +
	"\x13VERB_TYPE_KILL_PANE\x10\x05\x12\x18\n" +
	"\x14VERB_TYPE_SMART_JUMP\x10\x06\x12\x1a\n" +
	"\x16VERB_TYPE_TOGGLE_CARDS\x10\a\x12\x18\n" +
	"\x14VERB_TYPE_GROW_WIDTH\x10\b\x12\x1a\n" +
	"\x16VERB_TYPE_SHRINK_WIDTH\x10\t\x12\x17\n" +
	"\x13VERB_TYPE_MOVE_LEFT\x10\n" +
	"\x12\x18\n" +
	"\x14VERB_TYPE_MOVE_RIGHT\x10\v\x12\x18\n" +
	"\x14VERB_TYPE_FOCUS_LAST\x10\f*\x86\x01\n" +
	"\n" +
	"PaneStatus\x12\x14\n" +
	"\x10PANE_STATUS_IDLE\x10\x00\x12\x17\n" +
	"\x13PANE_STATUS_WORKING\x10\x01\x12\x1b\n" +
	"\x17PANE_STATUS_NEEDS_INPUT\x10\x02\x12\x14\n" +
	"\x10PANE_STATUS_DONE\x10\x03\x12\x16\n" +
	"\x12PANE_STATUS_FAILED\x10\x04*c\n" +
	"\tColorKind\x12\x13\n" +
	"\x0fCOLOR_KIND_NONE\x10\x00\x12\x14\n" +
	"\x10COLOR_KIND_BASIC\x10\x01\x12\x16\n" +
	"\x12COLOR_KIND_INDEXED\x10\x02\x12\x13\n" +
	"\x0fCOLOR_KIND_RGBA\x10\x03*f\n" +
	"\tMouseKind\x12\x14\n" +
	"\x10MOUSE_KIND_PRESS\x10\x00\x12\x16\n" +
	"\x12MOUSE_KIND_RELEASE\x10\x01\x12\x15\n" +
	"\x11MOUSE_KIND_MOTION\x10\x02\x12\x14\n" +
	"\x10MOUSE_KIND_WHEEL\x10\x03B7Z5github.com/lmorchard/wideboi/internal/protocol/wirepbb\x06proto3"

var (
	file_internal_protocol_wirepb_wideboi_proto_rawDescOnce sync.Once
	file_internal_protocol_wirepb_wideboi_proto_rawDescData []byte
)

func file_internal_protocol_wirepb_wideboi_proto_rawDescGZIP() []byte {
	file_internal_protocol_wirepb_wideboi_proto_rawDescOnce.Do(func() {
		file_internal_protocol_wirepb_wideboi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_wirepb_wideboi_proto_rawDesc), len(file_internal_protocol_wirepb_wideboi_proto_rawDesc)))
	})
	return file_internal_protocol_wirepb_wideboi_proto_rawDescData
}

var file_internal_protocol_wirepb_wideboi_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_internal_protocol_wirepb_wideboi_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_internal_protocol_wirepb_wideboi_proto_goTypes = []any{
	(VerbType)(0),             // 0: wideboi.protocol.VerbType
	(PaneStatus)(0),           // 1: wideboi.protocol.PaneStatus
	(ColorKind)(0),            // 2: wideboi.protocol.ColorKind
	(MouseKind)(0),            // 3: wideboi.protocol.MouseKind
	(*ColorData)(nil),         // 4: wideboi.protocol.ColorData
	(*StyleData)(nil),         // 5: wideboi.protocol.StyleData
	(*CellData)(nil),          // 6: wideboi.protocol.CellData
	(*LineData)(nil),          // 7: wideboi.protocol.LineData
	(*MsgPaneUpdate)(nil),     // 8: wideboi.protocol.MsgPaneUpdate
	(*PaneRow)(nil),           // 9: wideboi.protocol.PaneRow
	(*MsgPanePatch)(nil),      // 10: wideboi.protocol.MsgPanePatch
	(*ColumnData)(nil),        // 11: wideboi.protocol.ColumnData
	(*MsgLayoutSnapshot)(nil), // 12: wideboi.protocol.MsgLayoutSnapshot
	(*MsgPaneCreated)(nil),    // 13: wideboi.protocol.MsgPaneCreated
	(*MsgPaneClosed)(nil),     // 14: wideboi.protocol.MsgPaneClosed
	(*MsgPaneMetadata)(nil),   // 15: wideboi.protocol.MsgPaneMetadata
	(*ServerMessage)(nil),     // 16: wideboi.protocol.ServerMessage
	(*MsgAttach)(nil),         // 17: wideboi.protocol.MsgAttach
	(*MsgVerb)(nil),           // 18: wideboi.protocol.MsgVerb
	(*MsgMouse)(nil),          // 19: wideboi.protocol.MsgMouse
	(*KeyData)(nil),           // 20: wideboi.protocol.KeyData
	(*MsgInput)(nil),          // 21: wideboi.protocol.MsgInput
	(*MsgResize)(nil),         // 22: wideboi.protocol.MsgResize
	(*MsgScroll)(nil),         // 23: wideboi.protocol.MsgScroll
	(*MsgPaneResync)(nil),     // 24: wideboi.protocol.MsgPaneResync
	(*MsgDetach)(nil),         // 25: wideboi.protocol.MsgDetach
	(*MsgShutdown)(nil),       // 26: wideboi.protocol.MsgShutdown
	(*MsgStatusRequest)(nil),  // 27: wideboi.protocol.MsgStatusRequest
	(*ClientMessage)(nil),     // 28: wideboi.protocol.ClientMessage
	nil,                       // 29: wideboi.protocol.MsgLayoutSnapshot.PaneStatusesEntry
	nil,                       // 30: wideboi.protocol.MsgLayoutSnapshot.PaneTitlesEntry
	nil,                       // 31: wideboi.protocol.MsgPaneMetadata.UserVarsEntry
}
var file_internal_protocol_wirepb_wideboi_proto_depIdxs = []int32{
	2,  // 0: wideboi.protocol.ColorData.kind:type_name -> wideboi.protocol.ColorKind
	4,  // 1: wideboi.protocol.StyleData.fg:type_name -> wideboi.protocol.ColorData
	4,  // 2: wideboi.protocol.StyleData.bg:type_name -> wideboi.protocol.ColorData
	4,  // 3: wideboi.protocol.StyleData.underline_color:type_name -> wideboi.protocol.ColorData
	5,  // 4: wideboi.protocol.CellData.style:type_name -> wideboi.protocol.StyleData
	6,  // 5: wideboi.protocol.LineData.cells:type_name -> wideboi.protocol.CellData
	7,  // 6: wideboi.protocol.MsgPaneUpdate.lines:type_name -> wideboi.protocol.LineData
	6,  // 7: wideboi.protocol.PaneRow.cells:type_name -> wideboi.protocol.CellData
	9,  // 8: wideboi.protocol.MsgPanePatch.changed_rows:type_name -> wideboi.protocol.PaneRow
	11, // 9: wideboi.protocol.MsgLayoutSnapshot.columns:type_name -> wideboi.protocol.ColumnData
	29, // 10: wideboi.protocol.MsgLayoutSnapshot.pane_statuses:type_name -> wideboi.protocol.MsgLayoutSnapshot.PaneStatusesEntry
	30, // 11: wideboi.protocol.MsgLayoutSnapshot.pane_titles:type_name -> wideboi.protocol.MsgLayoutSnapshot.PaneTitlesEntry
	31, // 12: wideboi.protocol.MsgPaneMetadata.user_vars:type_name -> wideboi.protocol.MsgPaneMetadata.UserVarsEntry
	8,  // 13: wideboi.protocol.ServerMessage.pane_update:type_name -> wideboi.protocol.MsgPaneUpdate
	10, // 14: wideboi.protocol.ServerMessage.pane_patch:type_name -> wideboi.protocol.MsgPanePatch
	12, // 15: wideboi.protocol.ServerMessage.layout_snapshot:type_name -> wideboi.protocol.MsgLayoutSnapshot
	13, // 16: wideboi.protocol.ServerMessage.pane_created:type_name -> wideboi.protocol.MsgPaneCreated
	14, // 17: wideboi.protocol.ServerMessage.pane_closed:type_name -> wideboi.protocol.MsgPaneClosed
	15, // 18: wideboi.protocol.ServerMessage.pane_metadata:type_name -> wideboi.protocol.MsgPaneMetadata
	0,  // 19: wideboi.protocol.MsgVerb.verb:type_name -> wideboi.protocol.VerbType
	3,  // 20: wideboi.protocol.MsgMouse.kind:type_name -> wideboi.protocol.MouseKind
	20, // 21: wideboi.protocol.MsgInput.key:type_name -> wideboi.protocol.KeyData
	17, // 22: wideboi.protocol.ClientMessage.attach:type_name -> wideboi.protocol.MsgAttach
	18, // 23: wideboi.protocol.ClientMessage.verb:type_name -> wideboi.protocol.MsgVerb
	19, // 24: wideboi.protocol.ClientMessage.mouse:type_name -> wideboi.protocol.MsgMouse
	21, // 25: wideboi.protocol.ClientMessage.input:type_name -> wideboi.protocol.MsgInput
	22, // 26: wideboi.protocol.ClientMessage.resize:type_name -> wideboi.protocol.MsgResize
	23, // 27: wideboi.protocol.ClientMessage.scroll:type_name -> wideboi.protocol.MsgScroll
	24, // 28: wideboi.protocol.ClientMessage.pane_resync:type_name -> wideboi.protocol.MsgPaneResync
	25, // 29: wideboi.protocol.ClientMessage.detach:type_name -> wideboi.protocol.MsgDetach
	26, // 30: wideboi.protocol.ClientMessage.shutdown:type_name -> wideboi.protocol.MsgShutdown
	27, // 31: wideboi.protocol.ClientMessage.status_request:type_name -> wideboi.protocol.MsgStatusRequest
	1,  // 32: wideboi.protocol.MsgLayoutSnapshot.PaneStatusesEntry.value:type_name -> wideboi.protocol.PaneStatus
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_internal_protocol_wirepb_wideboi_proto_init() }
func file_internal_protocol_wirepb_wideboi_proto_init() {
	if File_internal_protocol_wirepb_wideboi_proto != nil {
		return
	}
	file_internal_protocol_wirepb_wideboi_proto_msgTypes[12].OneofWrappers = []any{
		(*ServerMessage_PaneUpdate)(nil),
		(*ServerMessage_PanePatch)(nil),
		(*ServerMessage_LayoutSnapshot)(nil),
		(*ServerMessage_PaneCreated)(nil),
		(*ServerMessage_PaneClosed)(nil),
		(*ServerMessage_PaneMetadata)(nil),
	}
	file_internal_protocol_wirepb_wideboi_proto_msgTypes[24].OneofWrappers = []any{
		(*ClientMessage_Attach)(nil),
		(*ClientMessage_Verb)(nil),
		(*ClientMessage_Mouse)(nil),
		(*ClientMessage_Input)(nil),
		(*ClientMessage_Resize)(nil),
		(*ClientMessage_Scroll)(nil),
		(*ClientMessage_PaneResync)(nil),
		(*ClientMessage_Detach)(nil),
		(*ClientMessage_Shutdown)(nil),
		(*ClientMessage_StatusRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_wirepb_wideboi_proto_rawDesc), len(file_internal_protocol_wirepb_wideboi_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_wirepb_wideboi_proto_goTypes,
		DependencyIndexes: file_internal_protocol_wirepb_wideboi_proto_depIdxs,
		EnumInfos:         file_internal_protocol_wirepb_wideboi_proto_enumTypes,
		MessageInfos:      file_internal_protocol_wirepb_wideboi_proto_msgTypes,
	}.Build()
	File_internal_protocol_wirepb_wideboi_proto = out.File
	file_internal_protocol_wirepb_wideboi_proto_goTypes = nil
	file_internal_protocol_wirepb_wideboi_proto_depIdxs = nil
}
