// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: internal/protocol/wideboi.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LayoutMode int32

const (
	LayoutMode_LAYOUT_SCROLL LayoutMode = 0
	LayoutMode_LAYOUT_CARDS  LayoutMode = 1
)

// Enum value maps for LayoutMode.
var (
	LayoutMode_name = map[int32]string{
		0: "LAYOUT_SCROLL",
		1: "LAYOUT_CARDS",
	}
	LayoutMode_value = map[string]int32{
		"LAYOUT_SCROLL": 0,
		"LAYOUT_CARDS":  1,
	}
)

func (x LayoutMode) Enum() *LayoutMode {
	p := new(LayoutMode)
	*p = x
	return p
}

func (x LayoutMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayoutMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_wideboi_proto_enumTypes[0].Descriptor()
}

func (LayoutMode) Type() protoreflect.EnumType {
	return &file_internal_protocol_wideboi_proto_enumTypes[0]
}

func (x LayoutMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayoutMode.Descriptor instead.
func (LayoutMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{0}
}

type PlacementKind int32

const (
	PlacementKind_PLACEMENT_FULL   PlacementKind = 0
	PlacementKind_PLACEMENT_SLIVER PlacementKind = 1
)

// Enum value maps for PlacementKind.
var (
	PlacementKind_name = map[int32]string{
		0: "PLACEMENT_FULL",
		1: "PLACEMENT_SLIVER",
	}
	PlacementKind_value = map[string]int32{
		"PLACEMENT_FULL":   0,
		"PLACEMENT_SLIVER": 1,
	}
)

func (x PlacementKind) Enum() *PlacementKind {
	p := new(PlacementKind)
	*p = x
	return p
}

func (x PlacementKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlacementKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_wideboi_proto_enumTypes[1].Descriptor()
}

func (PlacementKind) Type() protoreflect.EnumType {
	return &file_internal_protocol_wideboi_proto_enumTypes[1]
}

func (x PlacementKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlacementKind.Descriptor instead.
func (PlacementKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{1}
}

type ColorKind int32

const (
	ColorKind_COLOR_NONE    ColorKind = 0
	ColorKind_COLOR_BASIC   ColorKind = 1
	ColorKind_COLOR_INDEXED ColorKind = 2
	ColorKind_COLOR_RGBA    ColorKind = 3
)

// Enum value maps for ColorKind.
var (
	ColorKind_name = map[int32]string{
		0: "COLOR_NONE",
		1: "COLOR_BASIC",
		2: "COLOR_INDEXED",
		3: "COLOR_RGBA",
	}
	ColorKind_value = map[string]int32{
		"COLOR_NONE":    0,
		"COLOR_BASIC":   1,
		"COLOR_INDEXED": 2,
		"COLOR_RGBA":    3,
	}
)

func (x ColorKind) Enum() *ColorKind {
	p := new(ColorKind)
	*p = x
	return p
}

func (x ColorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_wideboi_proto_enumTypes[2].Descriptor()
}

func (ColorKind) Type() protoreflect.EnumType {
	return &file_internal_protocol_wideboi_proto_enumTypes[2]
}

func (x ColorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorKind.Descriptor instead.
func (ColorKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{2}
}

type MouseKind int32

const (
	MouseKind_MOUSE_PRESS   MouseKind = 0
	MouseKind_MOUSE_RELEASE MouseKind = 1
	MouseKind_MOUSE_MOTION  MouseKind = 2
	MouseKind_MOUSE_WHEEL   MouseKind = 3
)

// Enum value maps for MouseKind.
var (
	MouseKind_name = map[int32]string{
		0: "MOUSE_PRESS",
		1: "MOUSE_RELEASE",
		2: "MOUSE_MOTION",
		3: "MOUSE_WHEEL",
	}
	MouseKind_value = map[string]int32{
		"MOUSE_PRESS":   0,
		"MOUSE_RELEASE": 1,
		"MOUSE_MOTION":  2,
		"MOUSE_WHEEL":   3,
	}
)

func (x MouseKind) Enum() *MouseKind {
	p := new(MouseKind)
	*p = x
	return p
}

func (x MouseKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MouseKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_wideboi_proto_enumTypes[3].Descriptor()
}

func (MouseKind) Type() protoreflect.EnumType {
	return &file_internal_protocol_wideboi_proto_enumTypes[3]
}

func (x MouseKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MouseKind.Descriptor instead.
func (MouseKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{3}
}

type VerbType int32

const (
	VerbType_VERB_NONE         VerbType = 0
	VerbType_VERB_FOCUS_LEFT   VerbType = 1
	VerbType_VERB_FOCUS_RIGHT  VerbType = 2
	VerbType_VERB_NEW_COLUMN   VerbType = 3
	VerbType_VERB_CYCLE_WIDTH  VerbType = 4
	VerbType_VERB_KILL_PANE    VerbType = 5
	VerbType_VERB_SMART_JUMP   VerbType = 6
	VerbType_VERB_TOGGLE_CARDS VerbType = 7
	VerbType_VERB_GROW_WIDTH   VerbType = 8
	VerbType_VERB_SHRINK_WIDTH VerbType = 9
	VerbType_VERB_MOVE_LEFT    VerbType = 10
	VerbType_VERB_MOVE_RIGHT   VerbType = 11
	VerbType_VERB_FOCUS_LAST   VerbType = 12
)

// Enum value maps for VerbType.
var (
	VerbType_name = map[int32]string{
		0:  "VERB_NONE",
		1:  "VERB_FOCUS_LEFT",
		2:  "VERB_FOCUS_RIGHT",
		3:  "VERB_NEW_COLUMN",
		4:  "VERB_CYCLE_WIDTH",
		5:  "VERB_KILL_PANE",
		6:  "VERB_SMART_JUMP",
		7:  "VERB_TOGGLE_CARDS",
		8:  "VERB_GROW_WIDTH",
		9:  "VERB_SHRINK_WIDTH",
		10: "VERB_MOVE_LEFT",
		11: "VERB_MOVE_RIGHT",
		12: "VERB_FOCUS_LAST",
	}
	VerbType_value = map[string]int32{
		"VERB_NONE":         0,
		"VERB_FOCUS_LEFT":   1,
		"VERB_FOCUS_RIGHT":  2,
		"VERB_NEW_COLUMN":   3,
		"VERB_CYCLE_WIDTH":  4,
		"VERB_KILL_PANE":    5,
		"VERB_SMART_JUMP":   6,
		"VERB_TOGGLE_CARDS": 7,
		"VERB_GROW_WIDTH":   8,
		"VERB_SHRINK_WIDTH": 9,
		"VERB_MOVE_LEFT":    10,
		"VERB_MOVE_RIGHT":   11,
		"VERB_FOCUS_LAST":   12,
	}
)

func (x VerbType) Enum() *VerbType {
	p := new(VerbType)
	*p = x
	return p
}

func (x VerbType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerbType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_wideboi_proto_enumTypes[4].Descriptor()
}

func (VerbType) Type() protoreflect.EnumType {
	return &file_internal_protocol_wideboi_proto_enumTypes[4]
}

func (x VerbType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerbType.Descriptor instead.
func (VerbType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{4}
}

type ColumnData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnData) Reset() {
	*x = ColumnData{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnData) ProtoMessage() {}

func (x *ColumnData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnData.ProtoReflect.Descriptor instead.
func (*ColumnData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{0}
}

func (x *ColumnData) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *ColumnData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ColumnData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Rectangle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinX          int32                  `protobuf:"varint,1,opt,name=min_x,json=minX,proto3" json:"min_x,omitempty"`
	MinY          int32                  `protobuf:"varint,2,opt,name=min_y,json=minY,proto3" json:"min_y,omitempty"`
	MaxX          int32                  `protobuf:"varint,3,opt,name=max_x,json=maxX,proto3" json:"max_x,omitempty"`
	MaxY          int32                  `protobuf:"varint,4,opt,name=max_y,json=maxY,proto3" json:"max_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rectangle) Reset() {
	*x = Rectangle{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rectangle) ProtoMessage() {}

func (x *Rectangle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{1}
}

func (x *Rectangle) GetMinX() int32 {
	if x != nil {
		return x.MinX
	}
	return 0
}

func (x *Rectangle) GetMinY() int32 {
	if x != nil {
		return x.MinY
	}
	return 0
}

func (x *Rectangle) GetMaxX() int32 {
	if x != nil {
		return x.MaxX
	}
	return 0
}

func (x *Rectangle) GetMaxY() int32 {
	if x != nil {
		return x.MaxY
	}
	return 0
}

type PlacementData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Src           *Rectangle             `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst           *Rectangle             `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Z             int32                  `protobuf:"varint,4,opt,name=z,proto3" json:"z,omitempty"`
	Kind          PlacementKind          `protobuf:"varint,5,opt,name=kind,proto3,enum=protocol.PlacementKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacementData) Reset() {
	*x = PlacementData{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementData) ProtoMessage() {}

func (x *PlacementData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementData.ProtoReflect.Descriptor instead.
func (*PlacementData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{2}
}

func (x *PlacementData) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *PlacementData) GetSrc() *Rectangle {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *PlacementData) GetDst() *Rectangle {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *PlacementData) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlacementData) GetKind() PlacementKind {
	if x != nil {
		return x.Kind
	}
	return PlacementKind_PLACEMENT_FULL
}

type ColorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ColorKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=protocol.ColorKind" json:"kind,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // uint8 in Go
	R             uint32                 `protobuf:"varint,3,opt,name=r,proto3" json:"r,omitempty"`         // uint8 in Go
	G             uint32                 `protobuf:"varint,4,opt,name=g,proto3" json:"g,omitempty"`
	B             uint32                 `protobuf:"varint,5,opt,name=b,proto3" json:"b,omitempty"`
	A             uint32                 `protobuf:"varint,6,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorData) Reset() {
	*x = ColorData{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorData) ProtoMessage() {}

func (x *ColorData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorData.ProtoReflect.Descriptor instead.
func (*ColorData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{3}
}

func (x *ColorData) GetKind() ColorKind {
	if x != nil {
		return x.Kind
	}
	return ColorKind_COLOR_NONE
}

func (x *ColorData) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ColorData) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *ColorData) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *ColorData) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *ColorData) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

type StyleData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Fg             *ColorData             `protobuf:"bytes,1,opt,name=fg,proto3" json:"fg,omitempty"`
	Bg             *ColorData             `protobuf:"bytes,2,opt,name=bg,proto3" json:"bg,omitempty"`
	UnderlineColor *ColorData             `protobuf:"bytes,3,opt,name=underline_color,json=underlineColor,proto3" json:"underline_color,omitempty"`
	Underline      uint32                 `protobuf:"varint,4,opt,name=underline,proto3" json:"underline,omitempty"` // uint8 in Go
	Attrs          uint32                 `protobuf:"varint,5,opt,name=attrs,proto3" json:"attrs,omitempty"`         // uint8 in Go
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StyleData) Reset() {
	*x = StyleData{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StyleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StyleData) ProtoMessage() {}

func (x *StyleData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StyleData.ProtoReflect.Descriptor instead.
func (*StyleData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{4}
}

func (x *StyleData) GetFg() *ColorData {
	if x != nil {
		return x.Fg
	}
	return nil
}

func (x *StyleData) GetBg() *ColorData {
	if x != nil {
		return x.Bg
	}
	return nil
}

func (x *StyleData) GetUnderlineColor() *ColorData {
	if x != nil {
		return x.UnderlineColor
	}
	return nil
}

func (x *StyleData) GetUnderline() uint32 {
	if x != nil {
		return x.Underline
	}
	return 0
}

func (x *StyleData) GetAttrs() uint32 {
	if x != nil {
		return x.Attrs
	}
	return 0
}

type CellData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Style         *StyleData             `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellData) Reset() {
	*x = CellData{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellData) ProtoMessage() {}

func (x *CellData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellData.ProtoReflect.Descriptor instead.
func (*CellData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{5}
}

func (x *CellData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CellData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CellData) GetStyle() *StyleData {
	if x != nil {
		return x.Style
	}
	return nil
}

type LineData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*CellData            `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineData) Reset() {
	*x = LineData{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineData) ProtoMessage() {}

func (x *LineData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineData.ProtoReflect.Descriptor instead.
func (*LineData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{6}
}

func (x *LineData) GetCells() []*CellData {
	if x != nil {
		return x.Cells
	}
	return nil
}

type KeyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Mod           int32                  `protobuf:"varint,2,opt,name=mod,proto3" json:"mod,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`                                  // rune (int32)
	ShiftedCode   int32                  `protobuf:"varint,4,opt,name=shifted_code,json=shiftedCode,proto3" json:"shifted_code,omitempty"` // rune (int32)
	BaseCode      int32                  `protobuf:"varint,5,opt,name=base_code,json=baseCode,proto3" json:"base_code,omitempty"`          // rune (int32)
	IsRepeat      bool                   `protobuf:"varint,6,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyData) Reset() {
	*x = KeyData{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyData) ProtoMessage() {}

func (x *KeyData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyData.ProtoReflect.Descriptor instead.
func (*KeyData) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{7}
}

func (x *KeyData) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *KeyData) GetMod() int32 {
	if x != nil {
		return x.Mod
	}
	return 0
}

func (x *KeyData) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *KeyData) GetShiftedCode() int32 {
	if x != nil {
		return x.ShiftedCode
	}
	return 0
}

func (x *KeyData) GetBaseCode() int32 {
	if x != nil {
		return x.BaseCode
	}
	return 0
}

func (x *KeyData) GetIsRepeat() bool {
	if x != nil {
		return x.IsRepeat
	}
	return false
}

type MsgAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          int32                  `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAttach) Reset() {
	*x = MsgAttach{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAttach) ProtoMessage() {}

func (x *MsgAttach) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAttach.ProtoReflect.Descriptor instead.
func (*MsgAttach) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{8}
}

func (x *MsgAttach) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *MsgAttach) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type MsgVerb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verb          VerbType               `protobuf:"varint,1,opt,name=verb,proto3,enum=protocol.VerbType" json:"verb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgVerb) Reset() {
	*x = MsgVerb{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgVerb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVerb) ProtoMessage() {}

func (x *MsgVerb) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVerb.ProtoReflect.Descriptor instead.
func (*MsgVerb) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{9}
}

func (x *MsgVerb) GetVerb() VerbType {
	if x != nil {
		return x.Verb
	}
	return VerbType_VERB_NONE
}

type MsgFocusPane struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgFocusPane) Reset() {
	*x = MsgFocusPane{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgFocusPane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFocusPane) ProtoMessage() {}

func (x *MsgFocusPane) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFocusPane.ProtoReflect.Descriptor instead.
func (*MsgFocusPane) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{10}
}

func (x *MsgFocusPane) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

type MsgMouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Kind          MouseKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=protocol.MouseKind" json:"kind,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Button        int32                  `protobuf:"varint,5,opt,name=button,proto3" json:"button,omitempty"`
	Mod           int32                  `protobuf:"varint,6,opt,name=mod,proto3" json:"mod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMouse) Reset() {
	*x = MsgMouse{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMouse) ProtoMessage() {}

func (x *MsgMouse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMouse.ProtoReflect.Descriptor instead.
func (*MsgMouse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{11}
}

func (x *MsgMouse) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgMouse) GetKind() MouseKind {
	if x != nil {
		return x.Kind
	}
	return MouseKind_MOUSE_PRESS
}

func (x *MsgMouse) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MsgMouse) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MsgMouse) GetButton() int32 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *MsgMouse) GetMod() int32 {
	if x != nil {
		return x.Mod
	}
	return 0
}

type MsgInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Key           *KeyData               `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgInput) Reset() {
	*x = MsgInput{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInput) ProtoMessage() {}

func (x *MsgInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInput.ProtoReflect.Descriptor instead.
func (*MsgInput) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{12}
}

func (x *MsgInput) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgInput) GetKey() *KeyData {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MsgInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MsgResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          int32                  `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgResize) Reset() {
	*x = MsgResize{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResize) ProtoMessage() {}

func (x *MsgResize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResize.ProtoReflect.Descriptor instead.
func (*MsgResize) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{13}
}

func (x *MsgResize) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *MsgResize) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type MsgScroll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgScroll) Reset() {
	*x = MsgScroll{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgScroll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgScroll) ProtoMessage() {}

func (x *MsgScroll) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgScroll.ProtoReflect.Descriptor instead.
func (*MsgScroll) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{14}
}

func (x *MsgScroll) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgScroll) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type MsgDetach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDetach) Reset() {
	*x = MsgDetach{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDetach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDetach) ProtoMessage() {}

func (x *MsgDetach) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDetach.ProtoReflect.Descriptor instead.
func (*MsgDetach) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{15}
}

type MsgShutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgShutdown) Reset() {
	*x = MsgShutdown{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgShutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgShutdown) ProtoMessage() {}

func (x *MsgShutdown) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgShutdown.ProtoReflect.Descriptor instead.
func (*MsgShutdown) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{16}
}

// ClientEnvelope wraps all possible client-to-server messages
type ClientEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientEnvelope_Attach
	//	*ClientEnvelope_Verb
	//	*ClientEnvelope_FocusPane
	//	*ClientEnvelope_Mouse
	//	*ClientEnvelope_Input
	//	*ClientEnvelope_Resize
	//	*ClientEnvelope_Scroll
	//	*ClientEnvelope_Detach
	//	*ClientEnvelope_Shutdown
	Payload       isClientEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEnvelope) Reset() {
	*x = ClientEnvelope{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEnvelope) ProtoMessage() {}

func (x *ClientEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEnvelope.ProtoReflect.Descriptor instead.
func (*ClientEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{17}
}

func (x *ClientEnvelope) GetPayload() isClientEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientEnvelope) GetAttach() *MsgAttach {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Attach); ok {
			return x.Attach
		}
	}
	return nil
}

func (x *ClientEnvelope) GetVerb() *MsgVerb {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Verb); ok {
			return x.Verb
		}
	}
	return nil
}

func (x *ClientEnvelope) GetFocusPane() *MsgFocusPane {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_FocusPane); ok {
			return x.FocusPane
		}
	}
	return nil
}

func (x *ClientEnvelope) GetMouse() *MsgMouse {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Mouse); ok {
			return x.Mouse
		}
	}
	return nil
}

func (x *ClientEnvelope) GetInput() *MsgInput {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ClientEnvelope) GetResize() *MsgResize {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ClientEnvelope) GetScroll() *MsgScroll {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Scroll); ok {
			return x.Scroll
		}
	}
	return nil
}

func (x *ClientEnvelope) GetDetach() *MsgDetach {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Detach); ok {
			return x.Detach
		}
	}
	return nil
}

func (x *ClientEnvelope) GetShutdown() *MsgShutdown {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isClientEnvelope_Payload interface {
	isClientEnvelope_Payload()
}

type ClientEnvelope_Attach struct {
	Attach *MsgAttach `protobuf:"bytes,1,opt,name=attach,proto3,oneof"`
}

type ClientEnvelope_Verb struct {
	Verb *MsgVerb `protobuf:"bytes,2,opt,name=verb,proto3,oneof"`
}

type ClientEnvelope_FocusPane struct {
	FocusPane *MsgFocusPane `protobuf:"bytes,3,opt,name=focus_pane,json=focusPane,proto3,oneof"`
}

type ClientEnvelope_Mouse struct {
	Mouse *MsgMouse `protobuf:"bytes,4,opt,name=mouse,proto3,oneof"`
}

type ClientEnvelope_Input struct {
	Input *MsgInput `protobuf:"bytes,5,opt,name=input,proto3,oneof"`
}

type ClientEnvelope_Resize struct {
	Resize *MsgResize `protobuf:"bytes,6,opt,name=resize,proto3,oneof"`
}

type ClientEnvelope_Scroll struct {
	Scroll *MsgScroll `protobuf:"bytes,7,opt,name=scroll,proto3,oneof"`
}

type ClientEnvelope_Detach struct {
	Detach *MsgDetach `protobuf:"bytes,8,opt,name=detach,proto3,oneof"`
}

type ClientEnvelope_Shutdown struct {
	Shutdown *MsgShutdown `protobuf:"bytes,9,opt,name=shutdown,proto3,oneof"`
}

func (*ClientEnvelope_Attach) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Verb) isClientEnvelope_Payload() {}

func (*ClientEnvelope_FocusPane) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Mouse) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Input) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Resize) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Scroll) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Detach) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Shutdown) isClientEnvelope_Payload() {}

type MsgLayoutSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*ColumnData          `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Placements    []*PlacementData       `protobuf:"bytes,2,rep,name=placements,proto3" json:"placements,omitempty"`
	FocusPaneId   int32                  `protobuf:"varint,3,opt,name=focus_pane_id,json=focusPaneId,proto3" json:"focus_pane_id,omitempty"`
	PaneStatuses  map[int32]string       `protobuf:"bytes,4,rep,name=pane_statuses,json=paneStatuses,proto3" json:"pane_statuses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PaneTitles    map[int32]string       `protobuf:"bytes,5,rep,name=pane_titles,json=paneTitles,proto3" json:"pane_titles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Layout        LayoutMode             `protobuf:"varint,6,opt,name=layout,proto3,enum=protocol.LayoutMode" json:"layout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgLayoutSnapshot) Reset() {
	*x = MsgLayoutSnapshot{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgLayoutSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLayoutSnapshot) ProtoMessage() {}

func (x *MsgLayoutSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLayoutSnapshot.ProtoReflect.Descriptor instead.
func (*MsgLayoutSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{18}
}

func (x *MsgLayoutSnapshot) GetColumns() []*ColumnData {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *MsgLayoutSnapshot) GetPlacements() []*PlacementData {
	if x != nil {
		return x.Placements
	}
	return nil
}

func (x *MsgLayoutSnapshot) GetFocusPaneId() int32 {
	if x != nil {
		return x.FocusPaneId
	}
	return 0
}

func (x *MsgLayoutSnapshot) GetPaneStatuses() map[int32]string {
	if x != nil {
		return x.PaneStatuses
	}
	return nil
}

func (x *MsgLayoutSnapshot) GetPaneTitles() map[int32]string {
	if x != nil {
		return x.PaneTitles
	}
	return nil
}

func (x *MsgLayoutSnapshot) GetLayout() LayoutMode {
	if x != nil {
		return x.Layout
	}
	return LayoutMode_LAYOUT_SCROLL
}

type MsgPaneUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Lines         []*LineData            `protobuf:"bytes,4,rep,name=lines,proto3" json:"lines,omitempty"`
	CursorX       int32                  `protobuf:"varint,5,opt,name=cursor_x,json=cursorX,proto3" json:"cursor_x,omitempty"`
	CursorY       int32                  `protobuf:"varint,6,opt,name=cursor_y,json=cursorY,proto3" json:"cursor_y,omitempty"`
	CursorVisible bool                   `protobuf:"varint,7,opt,name=cursor_visible,json=cursorVisible,proto3" json:"cursor_visible,omitempty"`
	MouseTracking bool                   `protobuf:"varint,8,opt,name=mouse_tracking,json=mouseTracking,proto3" json:"mouse_tracking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPaneUpdate) Reset() {
	*x = MsgPaneUpdate{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPaneUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPaneUpdate) ProtoMessage() {}

func (x *MsgPaneUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPaneUpdate.ProtoReflect.Descriptor instead.
func (*MsgPaneUpdate) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{19}
}

func (x *MsgPaneUpdate) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgPaneUpdate) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *MsgPaneUpdate) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *MsgPaneUpdate) GetLines() []*LineData {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *MsgPaneUpdate) GetCursorX() int32 {
	if x != nil {
		return x.CursorX
	}
	return 0
}

func (x *MsgPaneUpdate) GetCursorY() int32 {
	if x != nil {
		return x.CursorY
	}
	return 0
}

func (x *MsgPaneUpdate) GetCursorVisible() bool {
	if x != nil {
		return x.CursorVisible
	}
	return false
}

func (x *MsgPaneUpdate) GetMouseTracking() bool {
	if x != nil {
		return x.MouseTracking
	}
	return false
}

type MsgPaneClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneId        int32                  `protobuf:"varint,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPaneClosed) Reset() {
	*x = MsgPaneClosed{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPaneClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPaneClosed) ProtoMessage() {}

func (x *MsgPaneClosed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPaneClosed.ProtoReflect.Descriptor instead.
func (*MsgPaneClosed) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{20}
}

func (x *MsgPaneClosed) GetPaneId() int32 {
	if x != nil {
		return x.PaneId
	}
	return 0
}

func (x *MsgPaneClosed) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// ServerEnvelope wraps all possible server-to-client messages
type ServerEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerEnvelope_LayoutSnapshot
	//	*ServerEnvelope_PaneUpdate
	//	*ServerEnvelope_PaneClosed
	Payload       isServerEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEnvelope) Reset() {
	*x = ServerEnvelope{}
	mi := &file_internal_protocol_wideboi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEnvelope) ProtoMessage() {}

func (x *ServerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_wideboi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEnvelope.ProtoReflect.Descriptor instead.
func (*ServerEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_protocol_wideboi_proto_rawDescGZIP(), []int{21}
}

func (x *ServerEnvelope) GetPayload() isServerEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerEnvelope) GetLayoutSnapshot() *MsgLayoutSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_LayoutSnapshot); ok {
			return x.LayoutSnapshot
		}
	}
	return nil
}

func (x *ServerEnvelope) GetPaneUpdate() *MsgPaneUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_PaneUpdate); ok {
			return x.PaneUpdate
		}
	}
	return nil
}

func (x *ServerEnvelope) GetPaneClosed() *MsgPaneClosed {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_PaneClosed); ok {
			return x.PaneClosed
		}
	}
	return nil
}

type isServerEnvelope_Payload interface {
	isServerEnvelope_Payload()
}

type ServerEnvelope_LayoutSnapshot struct {
	LayoutSnapshot *MsgLayoutSnapshot `protobuf:"bytes,1,opt,name=layout_snapshot,json=layoutSnapshot,proto3,oneof"`
}

type ServerEnvelope_PaneUpdate struct {
	PaneUpdate *MsgPaneUpdate `protobuf:"bytes,2,opt,name=pane_update,json=paneUpdate,proto3,oneof"`
}

type ServerEnvelope_PaneClosed struct {
	PaneClosed *MsgPaneClosed `protobuf:"bytes,3,opt,name=pane_closed,json=paneClosed,proto3,oneof"`
}

func (*ServerEnvelope_LayoutSnapshot) isServerEnvelope_Payload() {}

func (*ServerEnvelope_PaneUpdate) isServerEnvelope_Payload() {}

func (*ServerEnvelope_PaneClosed) isServerEnvelope_Payload() {}

var File_internal_protocol_wideboi_proto protoreflect.FileDescriptor

const file_internal_protocol_wideboi_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/protocol/wideboi.proto\x12\bprotocol\"S\n" +
	"\n" +
	"ColumnData\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"_\n" +
	"\tRectangle\x12\x13\n" +
	"\x05min_x\x18\x01 \x01(\x05R\x04minX\x12\x13\n" +
	"\x05min_y\x18\x02 \x01(\x05R\x04minY\x12\x13\n" +
	"\x05max_x\x18\x03 \x01(\x05R\x04maxX\x12\x13\n" +
	"\x05max_y\x18\x04 \x01(\x05R\x04maxY\"\xb1\x01\n" +
	"\rPlacementData\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12%\n" +
	"\x03src\x18\x02 \x01(\v2\x13.protocol.RectangleR\x03src\x12%\n" +
	"\x03dst\x18\x03 \x01(\v2\x13.protocol.RectangleR\x03dst\x12\f\n" +
	"\x01z\x18\x04 \x01(\x05R\x01z\x12+\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x17.protocol.PlacementKindR\x04kind\"\x82\x01\n" +
	"\tColorData\x12'\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x13.protocol.ColorKindR\x04kind\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\f\n" +
	"\x01r\x18\x03 \x01(\rR\x01r\x12\f\n" +
	"\x01g\x18\x04 \x01(\rR\x01g\x12\f\n" +
	"\x01b\x18\x05 \x01(\rR\x01b\x12\f\n" +
	"\x01a\x18\x06 \x01(\rR\x01a\"\xc7\x01\n" +
	"\tStyleData\x12#\n" +
	"\x02fg\x18\x01 \x01(\v2\x13.protocol.ColorDataR\x02fg\x12#\n" +
	"\x02bg\x18\x02 \x01(\v2\x13.protocol.ColorDataR\x02bg\x12<\n" +
	"\x0funderline_color\x18\x03 \x01(\v2\x13.protocol.ColorDataR\x0eunderlineColor\x12\x1c\n" +
	"\tunderline\x18\x04 \x01(\rR\tunderline\x12\x14\n" +
	"\x05attrs\x18\x05 \x01(\rR\x05attrs\"e\n" +
	"\bCellData\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12)\n" +
	"\x05style\x18\x03 \x01(\v2\x13.protocol.StyleDataR\x05style\"4\n" +
	"\bLineData\x12(\n" +
	"\x05cells\x18\x01 \x03(\v2\x12.protocol.CellDataR\x05cells\"\xa0\x01\n" +
	"\aKeyData\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x10\n" +
	"\x03mod\x18\x02 \x01(\x05R\x03mod\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12!\n" +
	"\fshifted_code\x18\x04 \x01(\x05R\vshiftedCode\x12\x1b\n" +
	"\tbase_code\x18\x05 \x01(\x05R\bbaseCode\x12\x1b\n" +
	"\tis_repeat\x18\x06 \x01(\bR\bisRepeat\"3\n" +
	"\tMsgAttach\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\"1\n" +
	"\aMsgVerb\x12&\n" +
	"\x04verb\x18\x01 \x01(\x0e2\x12.protocol.VerbTypeR\x04verb\"'\n" +
	"\fMsgFocusPane\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\"\x92\x01\n" +
	"\bMsgMouse\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12'\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x13.protocol.MouseKindR\x04kind\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x16\n" +
	"\x06button\x18\x05 \x01(\x05R\x06button\x12\x10\n" +
	"\x03mod\x18\x06 \x01(\x05R\x03mod\"\\\n" +
	"\bMsgInput\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12#\n" +
	"\x03key\x18\x02 \x01(\v2\x11.protocol.KeyDataR\x03key\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"3\n" +
	"\tMsgResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\":\n" +
	"\tMsgScroll\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\"\v\n" +
	"\tMsgDetach\"\r\n" +
	"\vMsgShutdown\"\xc6\x03\n" +
	"\x0eClientEnvelope\x12-\n" +
	"\x06attach\x18\x01 \x01(\v2\x13.protocol.MsgAttachH\x00R\x06attach\x12'\n" +
	"\x04verb\x18\x02 \x01(\v2\x11.protocol.MsgVerbH\x00R\x04verb\x127\n" +
	"\n" +
	"focus_pane\x18\x03 \x01(\v2\x16.protocol.MsgFocusPaneH\x00R\tfocusPane\x12*\n" +
	"\x05mouse\x18\x04 \x01(\v2\x12.protocol.MsgMouseH\x00R\x05mouse\x12*\n" +
	"\x05input\x18\x05 \x01(\v2\x12.protocol.MsgInputH\x00R\x05input\x12-\n" +
	"\x06resize\x18\x06 \x01(\v2\x13.protocol.MsgResizeH\x00R\x06resize\x12-\n" +
	"\x06scroll\x18\a \x01(\v2\x13.protocol.MsgScrollH\x00R\x06scroll\x12-\n" +
	"\x06detach\x18\b \x01(\v2\x13.protocol.MsgDetachH\x00R\x06detach\x123\n" +
	"\bshutdown\x18\t \x01(\v2\x15.protocol.MsgShutdownH\x00R\bshutdownB\t\n" +
	"\apayload\"\xf0\x03\n" +
	"\x11MsgLayoutSnapshot\x12.\n" +
	"\acolumns\x18\x01 \x03(\v2\x14.protocol.ColumnDataR\acolumns\x127\n" +
	"\n" +
	"placements\x18\x02 \x03(\v2\x17.protocol.PlacementDataR\n" +
	"placements\x12\"\n" +
	"\rfocus_pane_id\x18\x03 \x01(\x05R\vfocusPaneId\x12R\n" +
	"\rpane_statuses\x18\x04 \x03(\v2-.protocol.MsgLayoutSnapshot.PaneStatusesEntryR\fpaneStatuses\x12L\n" +
	"\vpane_titles\x18\x05 \x03(\v2+.protocol.MsgLayoutSnapshot.PaneTitlesEntryR\n" +
	"paneTitles\x12,\n" +
	"\x06layout\x18\x06 \x01(\x0e2\x14.protocol.LayoutModeR\x06layout\x1a?\n" +
	"\x11PaneStatusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fPaneTitlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfe\x01\n" +
	"\rMsgPaneUpdate\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\x12(\n" +
	"\x05lines\x18\x04 \x03(\v2\x12.protocol.LineDataR\x05lines\x12\x19\n" +
	"\bcursor_x\x18\x05 \x01(\x05R\acursorX\x12\x19\n" +
	"\bcursor_y\x18\x06 \x01(\x05R\acursorY\x12%\n" +
	"\x0ecursor_visible\x18\a \x01(\bR\rcursorVisible\x12%\n" +
	"\x0emouse_tracking\x18\b \x01(\bR\rmouseTracking\"E\n" +
	"\rMsgPaneClosed\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\x05R\x06paneId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\"\xdb\x01\n" +
	"\x0eServerEnvelope\x12F\n" +
	"\x0flayout_snapshot\x18\x01 \x01(\v2\x1b.protocol.MsgLayoutSnapshotH\x00R\x0elayoutSnapshot\x12:\n" +
	"\vpane_update\x18\x02 \x01(\v2\x17.protocol.MsgPaneUpdateH\x00R\n" +
	"paneUpdate\x12:\n" +
	"\vpane_closed\x18\x03 \x01(\v2\x17.protocol.MsgPaneClosedH\x00R\n" +
	"paneClosedB\t\n" +
	"\apayload*1\n" +
	"\n" +
	"LayoutMode\x12\x11\n" +
	"\rLAYOUT_SCROLL\x10\x00\x12\x10\n" +
	"\fLAYOUT_CARDS\x10\x01*9\n" +
	"\rPlacementKind\x12\x12\n" +
	"\x0ePLACEMENT_FULL\x10\x00\x12\x14\n" +
	"\x10PLACEMENT_SLIVER\x10\x01*O\n" +
	"\tColorKind\x12\x0e\n" +
	"\n" +
	"COLOR_NONE\x10\x00\x12\x0f\n" +
	"\vCOLOR_BASIC\x10\x01\x12\x11\n" +
	"\rCOLOR_INDEXED\x10\x02\x12\x0e\n" +
	"\n" +
	"COLOR_RGBA\x10\x03*R\n" +
	"\tMouseKind\x12\x0f\n" +
	"\vMOUSE_PRESS\x10\x00\x12\x11\n" +
	"\rMOUSE_RELEASE\x10\x01\x12\x10\n" +
	"\fMOUSE_MOTION\x10\x02\x12\x0f\n" +
	"\vMOUSE_WHEEL\x10\x03*\x99\x02\n" +
	"\bVerbType\x12\r\n" +
	"\tVERB_NONE\x10\x00\x12\x13\n" +
	"\x0fVERB_FOCUS_LEFT\x10\x01\x12\x14\n" +
	"\x10VERB_FOCUS_RIGHT\x10\x02\x12\x13\n" +
	"\x0fVERB_NEW_COLUMN\x10\x03\x12\x14\n" +
	"\x10VERB_CYCLE_WIDTH\x10\x04\x12\x12\n" +
	"\x0eVERB_KILL_PANE\x10\x05\x12\x13\n" +
	"\x0fVERB_SMART_JUMP\x10\x06\x12\x15\n" +
	"\x11VERB_TOGGLE_CARDS\x10\a\x12\x13\n" +
	"\x0fVERB_GROW_WIDTH\x10\b\x12\x15\n" +
	"\x11VERB_SHRINK_WIDTH\x10\t\x12\x12\n" +
	"\x0eVERB_MOVE_LEFT\x10\n" +
	"\x12\x13\n" +
	"\x0fVERB_MOVE_RIGHT\x10\v\x12\x13\n" +
	"\x0fVERB_FOCUS_LAST\x10\fB0Z.github.com/lmorchard/wideboi/internal/protocolb\x06proto3"

var (
	file_internal_protocol_wideboi_proto_rawDescOnce sync.Once
	file_internal_protocol_wideboi_proto_rawDescData []byte
)

func file_internal_protocol_wideboi_proto_rawDescGZIP() []byte {
	file_internal_protocol_wideboi_proto_rawDescOnce.Do(func() {
		file_internal_protocol_wideboi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_wideboi_proto_rawDesc), len(file_internal_protocol_wideboi_proto_rawDesc)))
	})
	return file_internal_protocol_wideboi_proto_rawDescData
}

var file_internal_protocol_wideboi_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_internal_protocol_wideboi_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_internal_protocol_wideboi_proto_goTypes = []any{
	(LayoutMode)(0),           // 0: protocol.LayoutMode
	(PlacementKind)(0),        // 1: protocol.PlacementKind
	(ColorKind)(0),            // 2: protocol.ColorKind
	(MouseKind)(0),            // 3: protocol.MouseKind
	(VerbType)(0),             // 4: protocol.VerbType
	(*ColumnData)(nil),        // 5: protocol.ColumnData
	(*Rectangle)(nil),         // 6: protocol.Rectangle
	(*PlacementData)(nil),     // 7: protocol.PlacementData
	(*ColorData)(nil),         // 8: protocol.ColorData
	(*StyleData)(nil),         // 9: protocol.StyleData
	(*CellData)(nil),          // 10: protocol.CellData
	(*LineData)(nil),          // 11: protocol.LineData
	(*KeyData)(nil),           // 12: protocol.KeyData
	(*MsgAttach)(nil),         // 13: protocol.MsgAttach
	(*MsgVerb)(nil),           // 14: protocol.MsgVerb
	(*MsgFocusPane)(nil),      // 15: protocol.MsgFocusPane
	(*MsgMouse)(nil),          // 16: protocol.MsgMouse
	(*MsgInput)(nil),          // 17: protocol.MsgInput
	(*MsgResize)(nil),         // 18: protocol.MsgResize
	(*MsgScroll)(nil),         // 19: protocol.MsgScroll
	(*MsgDetach)(nil),         // 20: protocol.MsgDetach
	(*MsgShutdown)(nil),       // 21: protocol.MsgShutdown
	(*ClientEnvelope)(nil),    // 22: protocol.ClientEnvelope
	(*MsgLayoutSnapshot)(nil), // 23: protocol.MsgLayoutSnapshot
	(*MsgPaneUpdate)(nil),     // 24: protocol.MsgPaneUpdate
	(*MsgPaneClosed)(nil),     // 25: protocol.MsgPaneClosed
	(*ServerEnvelope)(nil),    // 26: protocol.ServerEnvelope
	nil,                       // 27: protocol.MsgLayoutSnapshot.PaneStatusesEntry
	nil,                       // 28: protocol.MsgLayoutSnapshot.PaneTitlesEntry
}
var file_internal_protocol_wideboi_proto_depIdxs = []int32{
	6,  // 0: protocol.PlacementData.src:type_name -> protocol.Rectangle
	6,  // 1: protocol.PlacementData.dst:type_name -> protocol.Rectangle
	1,  // 2: protocol.PlacementData.kind:type_name -> protocol.PlacementKind
	2,  // 3: protocol.ColorData.kind:type_name -> protocol.ColorKind
	8,  // 4: protocol.StyleData.fg:type_name -> protocol.ColorData
	8,  // 5: protocol.StyleData.bg:type_name -> protocol.ColorData
	8,  // 6: protocol.StyleData.underline_color:type_name -> protocol.ColorData
	9,  // 7: protocol.CellData.style:type_name -> protocol.StyleData
	10, // 8: protocol.LineData.cells:type_name -> protocol.CellData
	4,  // 9: protocol.MsgVerb.verb:type_name -> protocol.VerbType
	3,  // 10: protocol.MsgMouse.kind:type_name -> protocol.MouseKind
	12, // 11: protocol.MsgInput.key:type_name -> protocol.KeyData
	13, // 12: protocol.ClientEnvelope.attach:type_name -> protocol.MsgAttach
	14, // 13: protocol.ClientEnvelope.verb:type_name -> protocol.MsgVerb
	15, // 14: protocol.ClientEnvelope.focus_pane:type_name -> protocol.MsgFocusPane
	16, // 15: protocol.ClientEnvelope.mouse:type_name -> protocol.MsgMouse
	17, // 16: protocol.ClientEnvelope.input:type_name -> protocol.MsgInput
	18, // 17: protocol.ClientEnvelope.resize:type_name -> protocol.MsgResize
	19, // 18: protocol.ClientEnvelope.scroll:type_name -> protocol.MsgScroll
	20, // 19: protocol.ClientEnvelope.detach:type_name -> protocol.MsgDetach
	21, // 20: protocol.ClientEnvelope.shutdown:type_name -> protocol.MsgShutdown
	5,  // 21: protocol.MsgLayoutSnapshot.columns:type_name -> protocol.ColumnData
	7,  // 22: protocol.MsgLayoutSnapshot.placements:type_name -> protocol.PlacementData
	27, // 23: protocol.MsgLayoutSnapshot.pane_statuses:type_name -> protocol.MsgLayoutSnapshot.PaneStatusesEntry
	28, // 24: protocol.MsgLayoutSnapshot.pane_titles:type_name -> protocol.MsgLayoutSnapshot.PaneTitlesEntry
	0,  // 25: protocol.MsgLayoutSnapshot.layout:type_name -> protocol.LayoutMode
	11, // 26: protocol.MsgPaneUpdate.lines:type_name -> protocol.LineData
	23, // 27: protocol.ServerEnvelope.layout_snapshot:type_name -> protocol.MsgLayoutSnapshot
	24, // 28: protocol.ServerEnvelope.pane_update:type_name -> protocol.MsgPaneUpdate
	25, // 29: protocol.ServerEnvelope.pane_closed:type_name -> protocol.MsgPaneClosed
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_internal_protocol_wideboi_proto_init() }
func file_internal_protocol_wideboi_proto_init() {
	if File_internal_protocol_wideboi_proto != nil {
		return
	}
	file_internal_protocol_wideboi_proto_msgTypes[17].OneofWrappers = []any{
		(*ClientEnvelope_Attach)(nil),
		(*ClientEnvelope_Verb)(nil),
		(*ClientEnvelope_FocusPane)(nil),
		(*ClientEnvelope_Mouse)(nil),
		(*ClientEnvelope_Input)(nil),
		(*ClientEnvelope_Resize)(nil),
		(*ClientEnvelope_Scroll)(nil),
		(*ClientEnvelope_Detach)(nil),
		(*ClientEnvelope_Shutdown)(nil),
	}
	file_internal_protocol_wideboi_proto_msgTypes[21].OneofWrappers = []any{
		(*ServerEnvelope_LayoutSnapshot)(nil),
		(*ServerEnvelope_PaneUpdate)(nil),
		(*ServerEnvelope_PaneClosed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_wideboi_proto_rawDesc), len(file_internal_protocol_wideboi_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_wideboi_proto_goTypes,
		DependencyIndexes: file_internal_protocol_wideboi_proto_depIdxs,
		EnumInfos:         file_internal_protocol_wideboi_proto_enumTypes,
		MessageInfos:      file_internal_protocol_wideboi_proto_msgTypes,
	}.Build()
	File_internal_protocol_wideboi_proto = out.File
	file_internal_protocol_wideboi_proto_goTypes = nil
	file_internal_protocol_wideboi_proto_depIdxs = nil
}
